apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-node-app
  template:
    metadata:
      labels:
        app: devops-node-app
    spec:
      containers:
      - name: devops-node-app
        image: your-dockerhub-username/devops-node-app:latest
        ports:
        - containerPort: 3000
